export const ActionTypes = {
  SET_MUSIC: "SET_MUSIC",
  SET_CURRENT_TIME: "SET_CURRENT_TIME",
  SET_IS_PLAYING: "SET_IS_PLAYING",
  SET_IS_ENDED: "SET_IS_ENDED",
  SET_VOLUME: "SET_VOLUME",
  REMOVE_MUSIC: "REMOVE_MUSIC",
};
